"""add otp attempt_count

Revision ID: 1ea62c42a6ce
Revises: 2203df049728
Create Date: 2026-05-29 08:58:04.732502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ea62c42a6ce'
down_revision: Union[str, None] = '2203df049728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'otp_codes',
        sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'attempt_count')
    # ### end Alembic commands ###
