"""add share_show_transactions

Revision ID: d52ebf415a21
Revises: c1d2e3f4a5b6
Create Date: 2026-06-26 13:31:02.821467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd52ebf415a21'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('share_show_transactions', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('rollup_groups', sa.Column('share_show_transactions', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('source_groups', sa.Column('share_show_transactions', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_groups', 'share_show_transactions')
    op.drop_column('rollup_groups', 'share_show_transactions')
    op.drop_column('labels', 'share_show_transactions')
    # ### end Alembic commands ###
